### ISSUE TITLE
专门拿来问问题的issue。。。

### ISSUE THREAD

**Issue by PhilCai1993** [DianQK/LearnRxSwift#1]
`fatal error: Failure converting from Jack's age is 18 to SectionsModel: file /Users/Phil/Desktop/DailyTutorial/ReactiveCocoa/LearnRxSwift/Pods/RxCocoa/RxCocoa/Common/RxCocoa.swift, line 340`

点击section的例子里面的cell后就crash了

**Comment by PhilCai1993** [comment]
不好意思，看到一半就操作了，没看到下文

**Comment by dianqk** [comment]
^^ 有什么问题都可以来提，稍后更新下一篇文章

**Comment by PhilCai1993** [comment]
昨天白天就在看RxSwift, 结果晚上就看到你的文章，哈哈，运气真好

**Comment by PhilCai1993** [comment]
http://t.swift.gg/d/18-006-subject
`ReplaySubject 都会发射完整的数据给观察者。`
应该是发送从“bufferSize”个之前的数据开始发送吧？

**Comment by dianqk** [comment]
已更新，`ReplaySubject` 是可以指定发射多少的以往的数据，调用 `createUnbounded` 时才是发射完整的数据。感谢~

**Comment by PhilCai1993** [comment]
受教了

**Comment by PhilCai1993** [comment]
``` swift
 let variable = Variable(1)
 variable.asObservable()
    .subscribe { (event) in
        print("Event1   ->   \(event)")
    }
    .addDisposableTo(disposeBag)

variable.value = 2
variable.value = 3
variable.asObservable()
    .subscribe { (event) in
        print("Event2   ->   \(event)")
    }
    .addDisposableTo(disposeBag)

variable.value = 4
variable.value = 5
```

输出:

```
Event1   ->   Next(1)
Event1   ->   Next(2)
Event1   ->   Next(3)
Event2   ->   Next(3) // 这里是最近一次发射的？
Event1   ->   Next(4)
Event2   ->   Next(4)
Event1   ->   Next(5)
Event2   ->   Next(5)
Event1   ->   Completed
Event2   ->   Completed
```

http://t.swift.gg/d/18-006-subject

订阅时就发射一次最近的~~序列~~(这里是应该指 Event 吗？序列的意思是什么呢？)，我们只需要在这里保留完整的数据（这里也不是很明白），那每一个订阅者都可以获得完整的数据

还有一个地方,  `ObserverType` 每次做 on , onNext 这类操作的时候, 是不是可以理解为它在发出一个信号(这里信号应该就是 Event ?)?

`Observable` 在 subscribe 的时候是不是可以理解为监听 on 发出来的信号?

我的理解有错误吗？
谢谢啦

**Comment by dianqk** [comment]
1. 对，发射的一个值，也就是事件  
2. 那段话我表述有一定欠缺，已经修改了一下  
3. `ObserverType` 是描述一个观察者的协议，`on` 的调用实际上就是当序列发射后，通过调用 `on` 来完成观察者做的事情，我们来看一下源码：

``` swift
public override func subscribe<O : ObserverType where O.E == Element>(observer: O) -> Disposable {
    return _synchronized_subscribe(observer)
}

func _synchronized_subscribe<O : ObserverType where O.E == E>(observer: O) -> Disposable {
    let key = _observers.insert(observer.asObserver())
    observer.on(.Next(_value))
    return SubscriptionDisposable(owner: self, key: key)
}
```

> 为了更好的理解 `on` 做了什么，我删除了一些代码。   

每当有值发射时，都会调用观察者的 `on` ，我觉得这里我们可以理解成 `on` 是被调用的，而不是发出东西。^^

**Comment by PhilCai1993** [comment]
感动😭
谢谢！

**Comment by PhilCai1993** [comment]
拿create为例

```
let createSequence = Observable<Int>.create { observer in
  print("create")
  sleep(1)
  observer.onNext(1)
  sleep(1)
  observer.onNext(2)
  sleep(1)
  observer.onCompleted()
  return NopDisposable.instance
}
let createSubscription = createSequence.subscribe { (event) in
  print(event)
}
```

LOG:

```
create
Next(1)
Next(2)
Completed
```

其实我一直感觉很混乱的地方是:
在create的closure里面，observer.onNext(1)，为什么我总是觉得是observer在主动发出”Event1“，然后在subscribe的closure里面，监控到了Event ?
但是你昨天说的`每当有值发射时，都会调用观察者的 on`,
我看了一下流程

```
Observable<Int>.create { observer in
   observer.onNext(1)
   ...
}
```

在func create的时候, 其实只是纪录了一下这个closure.
在createSequence.subscribe的时候, 就在指定的线程里执行AnonymousObservable的run方法，然后balabala...最后进入了 AnonymousObservableSink（是一个ObserverType） 的`func run(parent: Parent) -> Disposable`里面. 
run里就执行onNext(1)，onError,onCompletion这些方法（这就是你说的`都会调用观察者的 on`）
于是就`print(event)`了。

我描述应该很乱, 不知道有没有看懂。。。

`每当有值发射时` 的意思就是AnonymousObservable执行run的时候吗？

最后理一下：

Observable.create{closure1) －－－>

 生成了一个`AnonymousObservable` ,`AnonymousObservable` 纪录下了closure1 －－－> 

`AnonymousObservable` 在执行subscribe的时候 －－－> 

到指定的线程执行`AnonymousObservable` 的run 方法  －－－> 

调用到`AnonymousObservableSink` 的run方法 －－－> 

`func run(parent: Parent) -> Disposable` 其实就是
closure1开始执行

每天抽空看点RxSwift, 感觉挺烧脑的。。。

**Comment by dianqk** [comment]
关于这个 `observer.onNext(2)` 我觉得可以理解成，序列给观察者发射了一个 2 ，observer 用 `onNext(2)` 接收到了这个值。

也可以这样理解，`observer` 不是内部自己调用 `onNext` ，是别人调用的。。。

**Comment by PhilCai1993** [comment]
@DianQK 重新理了一下，你看看可对。。。

**Comment by PhilCai1993** [comment]
我不太能理解的是“发射了一个2”是哪个func呢？ run吗？

**Comment by PhilCai1993** [comment]
我发现好像拿PublishSubject比较好理解，

```
let publicSubject = PublishSubject<Int>()
publicSubject.onNext(1)
publicSubject.onNext(2)
publicSubject.subscribe { (event) in
  print("A: \(event)")
}
publicSubject.onNext(3)
publicSubject.onNext(4)
publicSubject.subscribe { (event) in
  print("B: \(event)")
}
```

Log:

```
A: Next(3)
A: Next(4)
```

它是一直到subscribe之后, 它的`_observers`` 就纪录了一个observer(观察者)，

然后publishSubject.onXXX的时候， `_observers``里的每个observer就被触发执行里on方法？

我觉得我好像理解对了？

**Comment by dianqk** [comment]
`PublishSubject` 可以这样理解。

== 建议不要过于强求理解这个，这个好比。。递归。。事实上 Rx 中函数的订阅（每个操作的执行）就类似于递归的过程。。。

**Comment by PhilCai1993** [comment]
😂我还是先用熟练了再看实现了。。。

**Comment by rayman-v** [comment]
项目里的Rx.playground 即使编译运行 `RxSwift` scheme，依然“no such module RxSwift”
![aa](https://cloud.githubusercontent.com/assets/4557143/14464651/4da008d8-0102-11e6-94cf-f59e0ae3275e.jpg)

**Comment by dianqk** [comment]
@rayman-v  HiHi ~ 我们其实可以新开一个 Issue 。。。

一般我遇到这个问题时，都是选择：

```
rm -rf ~/Library/Developer/Xcode/DerivedData/
```

**Comment by PhilCai1993** [comment]
有道理
