### ISSUE TITLE
第一节内容里的小问题

### ISSUE THREAD

**Issue by skyline75489** [DianQK/LearnRxSwift#3]
在 t.swift.gg 上没找到能注册的地方，只好到这里来评论了，望作者见谅。

[第一节](http://t.swift.gg/d/5-001-rxswift) 中提到：

> 不难理解，这部分的代码就是实时的执行：
> 
> `greetingLabel.text = "Greeting " + firstName.text + " " + lastName.text`
> 
> 这里的要求是实时，也就是说每当 fisrtName.text 或者 lastName.text 改变时， greetingLabel.text 都要随之改变。用前面的三行代码就很好的满足了需求。

这里的 `实时` 还特意进行了加粗标注。不过从实际上讲，这里的所谓 “实时”，并不是真正意义上的实时。这里这样描述可能会导致初学者理解上的偏差，以及和操作系统中的“实时”产生混淆。

**Comment by dianqk** [comment]
> 这里的要求是实时，也就是说每当 fisrtName.text 或者 lastName.text 改变时， greetingLabel.text 都要随之改变。用前面的三行代码就很好的满足了需求。

感谢指出，不过我在这里已经指出实时的含义了，有更合适的词推荐吗？

推荐最近的文章 https://medium.com/@DianQK/

**Comment by skyline75489** [comment]
我感觉作为第一章内容，只要指出这里的 value 绑定的功能就可以了，不如改成这样：

> 所谓绑定，可以理解为每当 fisrtName.text 或者 lastName.text 改变时，都会执行
> 
> `greetingLabel.text = "Greeting " + firstName.text + " " + lastName.text`
> 
> 也就是说 greetingLabel.text 会随着改变。用前面的三行代码就很好的满足了把一个值同界面显示的内容“绑定”起来的需求。

**Comment by skyline75489** [comment]
顺便提一下， t.swift.gg 上不能评论， medium 这个网站又是半墙不墙的状态，作者想让教程被更多人看到进而以推广 Rx 的话，不如考虑下把教程直接搬到 Github 上作为开源项目，目前看 Github 还算是比较安全的。

**Comment by dianqk** [comment]
好的~

> 主要最近事情有些多，忙不过来的样子 Orz
